export const INIT_DATA="INIT_DATA"
export const FETCH_DATA_SUCCESS="FETCH_DATA_SUCCESS"
export const FETCH_DATA_FAILED="FETCH_DATA_FAILED"

// Category

export const INIT_CATEGORY="INIT_CATEGORY"
export const FETCH_CATEGORY_SUCCESS="FETCH_CATEGORY_SUCCESS"
export const FETCH_CATEGORY_FAILED="FETCH_CATEGORY_FAILED"

export const INIT_ADD_DATA="INIT_ADD_DATA"
export const ADD_DATA_SUCCESS="ADD_DATA_SUCCESS"
export const ADD_DATA_FAILED="ADD_DATA_FAILED"

export const INIT_DELETE_CATEGORY="INIT_DELETE_CATEGORY"
export const DELETE_DATA_SUCCESS="DELETE_DATA_SUCCESS"
export const DELETE_DATA_FAILED="DELETE_DATA_FAILED"

export const INIT_EDIT_CATEGORY="INIT_EDIT_CATEGORY"
export const EDIT_DATA_SUCCESS="EDIT_DATA_SUCCESS"
export const EDIT_DATA_FAILED="EDIT_DATA_FAILED"

export const INIT_SINGLE_CATEGORY="INIT_SINGLE_CATEGORY"
export const SINGLE_DATA_SUCCESS="SINGLE_DATA_SUCCESS"
export const SINGLE_DATA_FAILED="SINGLE_DATA_FAILED"


//Auth

export const INIT_ADMIN_LOGIN="INIT_ADMIN_LOGIN"
export const ADMIN_LOGIN_SUCCESS="ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAILED="ADMIN_LOGIN_FAILED"

export const INIT_ADMIN_LOGOUT="INIT_ADMIN_LOGOUT"
export const ADMIN_LOGOUT_SUCCESS="ADMIN_LOGOUT_SUCCESS"
export const ADMIN_LOGOUT_FAILED="ADMIN_LOGOUT_FAILED"

export const INIT_CHANGE_PASSWORD="INIT_CHANGE_PASSWORD"
export const CHANGE_PASSWORD_SUCCESS="CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAILED="CHANGE_PASSWORD_FAILED"


// User

export const INIT_FETCH_USER="INIT_FETCH_USER"
export const FETCH_USER_SUCCESS="FETCH_USER_SUCCESS"
export const FETCH_USER_FAILED="FETCH_USER_FAILED"

export const INIT_EDIT_USER="INIT_EDIT_USER"
export const EDIT_USER_SUCCESS="EDIT_USER_SUCCESS"
export const EDIT_USER_FAILED="EDIT_USER_FAILED"

export const INIT_FORGOT_PASSWORD="INIT_FORGOT_PASSWORD"
export const FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAILED="FORGOT_PASSWORD_FAILED"

export const INIT_RESET_PASSWORD="INIT_RESET_PASSWORD"
export const RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAILED="RESET_PASSWORD_FAILED"


// Category

export const INIT_EVENT="INIT_EVENT"
export const FETCH_EVENT_SUCCESS="FETCH_EVENT_SUCCESS"
export const FETCH_EVENT_FAILED="FETCH_EVENT_FAILED"

export const INIT_EVENT_DATA="INIT_EVENT_DATA"
export const ADD_EVENT_SUCCESS="ADD_EVENT_SUCCESS"
export const ADD_EVENT_FAILED="ADD_EVENT_FAILED"

export const INIT_DELETE_EVENT="INIT_DELETE_EVENT"
export const DELETE_EVENT_SUCCESS="DELETE_EVENT_SUCCESS"
export const DELETE_EVENT_FAILED="DELETE_EVENT_FAILED"

export const INIT_EDIT_EVENT="INIT_EDIT_EVENT"
export const EDIT_EVENT_SUCCESS="EDIT_EVENT_SUCCESS"
export const EDIT_EVENT_FAILED="EDIT_EVENT_FAILED"

export const INIT_SINGLE_EVENT="INIT_SINGLE_EVENT"
export const SINGLE_EVENT_SUCCESS="SINGLE_EVENT_SUCCESS"
export const SINGLE_EVENT_FAILED="SINGLE_EVENT_FAILED"

export const INIT_FETCH_DASHBOARD="INIT_FETCH_DASHBOARD"
export const FETCH_DASHBOARD_SUCCESS="FETCH_DASHBOARD_SUCCESS"
export const FETCH_DASHBOARD_FAILED="FETCH_DASHBOARD_FAILED"