export const INIT_DATA="INIT_DATA"
export const FETCH_DATA_SUCCESS="FETCH_DATA_SUCCESS"
export const FETCH_DATA_FAILED="FETCH_DATA_FAILED"

export const INIT_CATEGORY="INIT_CATEGORY"
export const FETCH_CATEGORY_SUCCESS="FETCH_CATEGORY_SUCCESS"
export const FETCH_CATEGORY_FAILED="FETCH_CATEGORY_FAILED"

export const INIT_ADD_DATA="INIT_ADD_DATA"
export const ADD_DATA_SUCCESS="ADD_DATA_SUCCESS"
export const ADD_DATA_FAILED="ADD_DATA_FAILED"

export const INIT_DELETE_CATEGORY="INIT_DELETE_CATEGORY"
export const DELETE_DATA_SUCCESS="DELETE_DATA_SUCCESS"
export const DELETE_DATA_FAILED="DELETE_DATA_FAILED"

export const INIT_EDIT_CATEGORY="INIT_EDIT_CATEGORY"
export const EDIT_DATA_SUCCESS="EDIT_DATA_SUCCESS"
export const EDIT_DATA_FAILED="EDIT_DATA_FAILED"

export const INIT_SINGLE_CATEGORY="INIT_SINGLE_CATEGORY"
export const SINGLE_DATA_SUCCESS="SINGLE_DATA_SUCCESS"
export const SINGLE_DATA_FAILED="SINGLE_DATA_FAILED"